### ISSUE TITLE
Why the queries should not contain operations related with uncertain predicates？

### ISSUE THREAD

**Issue by imnujf** [Caesar11/gStore#2]
Operations related with uncertain predicates are more commonly used query request. Why dose the gStore support such operations? Is it due to the efficiency of storage or query?

**Comment by qzxx-syzz** [comment]
Notice that gStore need to use VStree index to filter out the candidates of each variable in query. However, the current VStree can find nothing about the predicates because we only build nodes for subject/object variables of SPARQL queries in the VStree.
The idea of VStree is presented in the gStore-VLDB paper, which  improve the efficiency while neglecting uncertain predicates.
We will try to deal with this problem later:)

**Comment by imnujf** [comment]
thank you very much.
