### ISSUE TITLE
Python API was removed?

### ISSUE THREAD

**Issue by zhangxiaoyang** [Caesar11/gStore#5]
I wrote python api for gstore and it was merged (see <https://github.com/Caesar11/gStore/pull/3>).

But the newest version of gstore(<https://github.com/Caesar11/gStore/commit/02e54e2c1762d1aaefe2feb02149136f8edf6859>) removed it.

Why:cry:

**Comment by bookug** [comment]
I am sorry to hear that>_<, and I readded your python api into gStore just now.
It is totally my mistake because I missed the python api when merging two branches yesterday.
Your job is helpful to us and we have added you into the thanking list:)

**Comment by zouleipku** [comment]
Hi Xiaoyang,

Thanks for your interest in our gstore project.

Recently, we are working on collecting some information about the gStore
project.  

Could you please give us some information about your project using gStore ?
For example, you can give us how large (the number of triples) of your
knowledge graph and the simple description of your project.

Many thanks for your contribution to the project.


Appreciated.

Best,
Lei
― 
Lei Zou, Ph.D.
Associate Professor,
Institute of Computer Science & Technology, Peking University, China
Tel:  +86-10-82529643
Fax: +86-10-62754532
Email: zoulei@pku.edu.cn
Website:  http://www.icst.pku.edu.cn/intro/leizou/index.html


On 5/20/16, 9:16 PM， "Bookug Lobert" <notifications@github.com> wrote:
On Dec 24, 2013, at 9:48 AM, Lei Zou <zoulei@pku.edu.cn> wrote:
On 5/20/16, 9:16 PM


I am sorry to hear that>_<, and I readded your python api into gStore just
now.
It is totally my mistake because I missed the python api when merging two
branches yesterday.
Your job is helpful to us and we have added you into the thanking list:)

―
You are receiving this because you are subscribed to this thread.
Reply to this email directly or view it on GitHub
<https://github.com/Caesar11/gStore/issues/5#issuecomment-220602674>

**Comment by zhangxiaoyang** [comment]
We are constructing a academic knowledge graph with gstore, but due to confidential issue, I am afraid that I can not give more details.

**Comment by bookug** [comment]
That is ok, thank you!~

**Comment by WenJieLiHnu** [comment]
<p>111</p>
