### ISSUE TITLE
make failed 

### ISSUE THREAD

**Issue by chanhz** [Caesar11/gStore#6]
Hi,I have gcc,readline,mpich,make installed,but still make failed  at last.

[root@localhost gStore]# make
mpicxx -c -Wall -g  Main/gloadD.cpp -I./tools/libantlr3c-3.4/ -I./tools/libantlr3c-3.4/include  -o .objs/gloadD.o 
make: mpicxx: Command not found
make: *** [.objs/gloadD.o] Error 12

Should  I install mpicxx?
What's more, the last version, which is with docs details,I excute  command :

[root@localhost mygStore]# bin/gload aaa ./data/LUBM_10.n3 
profile: init.conf
appname: [setting]
app found!
keyname: mode
key found!
KeyVal: single
gload...
argc: 3	DB_store:aaa	RDF_data: ./data/LUBM_10.n3	
realpath ./data/LUBM_10.n3 > .tmp/ans.txt
sh: realpath: command not found
ans: 
begin encode RDF from :  ...
sub2id&pre2id&obj2id: Fail to open :

The docs ,I can't find it in this vesion 

My OS is cent os 6.6 x86_64.

**Comment by bookug** [comment]
For the first question, mpicxx is a compiler, which is required by distributed gStore system.
For the second question, realpath is a shell command to find out the real path of a link.
(this means you can type just a soft link instead of a full path)
For most Linux systems, realpath is installed by default.
If not, try to install it.
If unable to install, it is advised to try another newer system or just comment out the source code containg realpath in gStore system:)

**Comment by WenJieLiHnu** [comment]
<p>111</p>
